export const DataEng = {
  title: "Contact Form",
  name: "Name:",
  namePlaceholder: "Enter Your Name",
  email: "Email:",
  emailPlaceholder: "Enter Your email",
  tel: "Telephone Number:",
  telPlaceholder: "Enter Your Tel. Number (optional)",
  subject: "Subject:",
  subjectPlaceholder: "Subject",
  message: "Message:",
  messagePlaceholder: "Enter your message",
  submit: "Send Message",
  successMessage: "Your message has been sent.",
  sendAnother: "Send another message",
  close: "Close contact form",
};
export const DataPL = {
  title: "Formularz Kontaktowy",
  name: "Imię i Nazwisko",
  namePlaceholder: "Wprowadź swoje imię i nazwisko",
  email: "Email:",
  emailPlaceholder: "Wprowadź swój adres email",
  tel: "Numer Telefonu:",
  telPlaceholder: "Wprowadź swój numer telefonu (opcjonalne)",
  subject: "Temat:",
  subjectPlaceholder: "Wprowadź temat wiadomości",
  message: "Wiadomość:",
  messagePlaceholder: "Wprowadź wiadomość",
  submit: "Wyślij wiadomość",
  successMessage: "Twoja wiadomość została wysłana.",
  sendAnother: "Wyślij inną wiadomość",
  close: "Zamknij formularz kontaktowy",
};
